### ISSUE TITLE
comment lines is too harsh

### ISSUE THREAD

**Issue by ztdawang** [kolunmi/ttyscheme#3]
When writing shell scripts with vim, the color of the comment lines in them is too harsh

**Comment by ztdawang** [comment]
ttyscheme cyberpunk
or
ttyscheme sublette

**Comment by kolunmi** [comment]
Hello! can you specify which color is too harsh for each theme you mentioned?

**Comment by ztdawang** [comment]
![image](https://user-images.githubusercontent.com/22386267/201232419-338f3f35-fe0c-4591-aa98-3a4b8b79c82c.png)

![image](https://user-images.githubusercontent.com/22386267/201233067-4e5961af-33f2-4c6a-b086-a2bd95e68cb5.png)

**Comment by ztdawang** [comment]
I am using mobaxterm terminal emulator and the color theme I set is "Solarized dark". 

I think the comment line should be a gray, darker color.

However, I found out that ttyscheme is also a shell script, so I can try to change the color values myself. Thanks for your work!

**Comment by ztdawang** [comment]
![image](https://user-images.githubusercontent.com/22386267/201242939-38bb2396-37cc-4e17-846c-3995c9aa7c38.png)
![image](https://user-images.githubusercontent.com/22386267/201242998-f9a07612-c6c9-43ae-8d82-473b9bfbcbc1.png)


sublette=             #413345 #ee5577 #55ee77 #ffdd88 #5588ff #ff77cc #44eeee #ccced0   #405570 #ee6655 #99ee77 #f1f752 #    77bbff #aa88ff #97b0ae #ffffee

**Comment by kolunmi** [comment]
Ok, I added your version under the name 'sublette_alt'. Did you also have a suggestion for cyberpunk?

**Comment by ztdawang** [comment]
Not bad, but again, need to change the color of the comment line. BTW, this Cyberpunk color scheme looks cool.
https://github.com/Roboron3042/Cyberpunk-Neon
https://gogh-co.github.io/Gogh/

**Comment by kolunmi** [comment]
That will be up to the vim config to assign the colors. Also I added the cyberpunk theme you linked.
